### ISSUE TITLE
摄像头

### ISSUE THREAD

**Issue by erlan-11** [kkbo8005/mitan#1]
为什么打开后会莫名自动打开摄像头？

**Comment by EdinLyle** [comment]
你可以找原作者去询问,我是pull过来的

**Comment by kkbo8005** [comment]
直接在https://github.com/kkbo8005/mitan/下载试试呢，应该不会的，第一次遇到有人反馈这个，或则+v我直接发最新的给你看看

**Comment by kkbo8005** [comment]
> 为什么打开后会莫名自动打开摄像头？

直接在[https://github.com/kkbo8005/mitan/下载试试呢，应该不会的，第一次遇到有人反馈这个，或则+v我直接发最新的给你看看](https://github.com/kkbo8005/mitan/%E4%B8%8B%E8%BD%BD%E8%AF%95%E8%AF%95%E5%91%A2%EF%BC%8C%E5%BA%94%E8%AF%A5%E4%B8%8D%E4%BC%9A%E7%9A%84%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E9%81%87%E5%88%B0%E6%9C%89%E4%BA%BA%E5%8F%8D%E9%A6%88%E8%BF%99%E4%B8%AA%EF%BC%8C%E6%88%96%E5%88%99+v%E6%88%91%E7%9B%B4%E6%8E%A5%E5%8F%91%E6%9C%80%E6%96%B0%E7%9A%84%E7%BB%99%E4%BD%A0%E7%9C%8B%E7%9C%8B)

**Comment by erlan-11** [comment]
好像问题出现在英伟达不是软件本身

**Comment by kkbo8005** [comment]
OK OK，不是就好，在微信群里别人 提醒我，吓我一跳，还以为被投毒了。

erlan-11 ***@***.***> 于2024年5月6日周一 21:51写道：
